# Site settings
title: Cats on Code
email: hello@jamiepilgrim.com
description: > # this means to ignore newlines until "baseurl:"
  The cattiest web development blog on the interwebz.  
url: "pilgrimmemoirs.github.io" # the base hostname & protocol for your site
url2: "http://illbringthedonuts.com"
twitter_username: pilgrimmemoirs
github_username:  pilgrimmemoirs
# Build settings
markdown: kramdown
permalink: /:title

